'use client';

import { Suspense } from 'react';
import { useSearchParams } from 'next/navigation';
import Link from 'next/link';
import { CheckCircle, Sparkles, Mail, Download, Shield, Target } from 'lucide-react';

function SuccessContent() {
  const searchParams = useSearchParams();
  const sessionId = searchParams.get('session_id');
  const type = searchParams.get('type'); // 'custom_qron' | 'subscription' | etc.

  const isCustomQron = type === 'custom_qron';

  return (
    <div className="min-h-screen protocol-bg text-white flex items-center justify-center p-4">
      <div className="w-full max-w-lg">

        {/* Protocol badge */}
        <div className="flex justify-center mb-8">
          <span className="protocol-badge">
            <Shield className="w-3 h-3" />
            AuthiChain Protocol — Verified
          </span>
        </div>

        {/* Main card */}
        <div className="protocol-card p-8 text-center">
          {/* Animated check */}
          <div className="flex justify-center mb-6">
            <div style={{
              width: 80, height: 80,
              borderRadius: '50%',
              background: 'rgba(201,162,39,0.1)',
              border: '2px solid rgba(201,162,39,0.4)',
              boxShadow: '0 0 32px rgba(201,162,39,0.2)',
              display: 'flex', alignItems: 'center', justifyContent: 'center',
            }}>
              <CheckCircle className="w-10 h-10" style={{ color: '#c9a227' }} />
            </div>
          </div>

          <h1 className="text-3xl font-extrabold gold-text mb-3">
            Payment Confirmed
          </h1>
          <p className="text-base mb-8" style={{ color: '#9e9e9e' }}>
            {isCustomQron
              ? 'Your custom QRON is being generated by fal.ai and will arrive in your inbox within 5 minutes.'
              : 'Your credits have been added and your account is upgraded. Start generating QRONs now.'}
          </p>

          {/* Steps */}
          <div className="space-y-3 mb-8 text-left">
            {(isCustomQron ? [
              { icon: <CheckCircle className="w-4 h-4" />, text: 'Payment confirmed via Stripe', done: true },
              { icon: <Sparkles className="w-4 h-4" />, text: 'fal.ai illusion-diffusion generating your QRON', done: false },
              { icon: <Shield className="w-4 h-4" />, text: 'AuthiChain Ed25519 signature applied', done: false },
              { icon: <Mail className="w-4 h-4" />, text: 'High-res file delivered to your email', done: false },
            ] : [
              { icon: <CheckCircle className="w-4 h-4" />, text: 'Payment confirmed via Stripe', done: true },
              { icon: <CheckCircle className="w-4 h-4" />, text: 'Generation credits added to your account', done: true },
              { icon: <Sparkles className="w-4 h-4" />, text: 'Ready to generate QRONs now', done: true },
            ]).map(({ icon, text, done }, i) => (
              <div key={i} className="flex items-center gap-3 px-4 py-3 rounded-lg"
                   style={{ background: done ? 'rgba(201,162,39,0.08)' : 'rgba(255,255,255,0.03)', border: `1px solid ${done ? 'rgba(201,162,39,0.2)' : 'rgba(255,255,255,0.06)'}` }}>
                <span style={{ color: done ? '#c9a227' : '#3a3a3a' }}>{icon}</span>
                <span className="text-sm" style={{ color: done ? '#c8c8c8' : '#4a4a4a' }}>{text}</span>
              </div>
            ))}
          </div>

          {/* CTAs */}
          <div className="space-y-3">
            <Link href="/" className="btn-gold w-full py-3 rounded-xl flex items-center justify-center gap-2 font-bold no-underline">
              <Sparkles className="w-4 h-4" />
              Generate a QRON
            </Link>
            {isCustomQron && (
              <Link href="/demo" className="btn-outline-gold w-full py-3 rounded-xl flex items-center justify-center gap-2 no-underline">
                <Target className="w-4 h-4" />
                Browse Demo Gallery
              </Link>
            )}
          </div>

          {sessionId && (
            <p className="text-xs mt-6" style={{ color: '#2a2a2a' }}>
              Ref: {sessionId.slice(0, 24)}…
            </p>
          )}
        </div>

        <p className="text-center text-xs mt-6" style={{ color: '#3a3a3a' }}>
          Questions? Contact{' '}
          <a href="mailto:Z@authichain.com" style={{ color: '#c9a227' }}>Z@authichain.com</a>
        </p>
      </div>
    </div>
  );
}

export default function Success() {
  return (
    <Suspense fallback={
      <div className="min-h-screen protocol-bg flex items-center justify-center">
        <div className="text-center">
          <div className="animate-spin rounded-full h-12 w-12 border-2 mx-auto mb-4"
               style={{ borderColor: 'rgba(201,162,39,0.3)', borderTopColor: '#c9a227' }} />
          <p style={{ color: '#6b6b6b' }}>Processing…</p>
        </div>
      </div>
    }>
      <SuccessContent />
    </Suspense>
  );
}
