import type { Metadata } from 'next'
import Link from 'next/link'

export const metadata: Metadata = {
  title: 'QRON AI QR Code Gallery — Real Examples That Scan',
  description: 'Browse 12 AI-generated QR code art examples. Cosmic Space, Cannabis, Cyberpunk, Nature, Abstract, Retro Vintage. All 100% scannable.',
  alternates: { canonical: 'https://qron.space/gallery' },
}

async function getDemos() {
  try {
    const res = await fetch('https://qron.space/api/demos', { next: { revalidate: 3600 } })
    const d = await res.json()
    return d.demos || []
  } catch {
    return []
  }
}

const STYLE_LABELS: Record<string,string> = {
  space: 'Cosmic Space', cannabis: 'Cannabis', cyberpunk: 'Cyberpunk',
  nature: 'Nature', abstract: 'Abstract', retro: 'Retro Vintage',
}

export default async function GalleryPage() {
  const demos = await getDemos()
  const gold = '#c9a227'
  return (
    <div style={{background:'#0a0a0a',color:'#e5e5e5',minHeight:'100vh',fontFamily:'system-ui,sans-serif'}}>
      <div style={{maxWidth:'1100px',margin:'0 auto',padding:'56px 20px 80px'}}>
        <Link href="/" style={{color:'#555',fontSize:'12px',fontWeight:700,textDecoration:'none',letterSpacing:'.1em',textTransform:'uppercase',display:'block',marginBottom:'24px'}}>
          ← QRON
        </Link>
        <h1 style={{fontSize:'clamp(1.8rem,4vw,2.6rem)',fontWeight:900,marginBottom:'12px'}}>
          AI QR Code Gallery
        </h1>
        <p style={{color:'#888',fontSize:'16px',marginBottom:'40px',maxWidth:'600px',lineHeight:1.6}}>
          Every QR code below was generated by AI and links to a live URL. Scan any with your phone — they all work.
          6 styles, from cosmic to cannabis.
        </p>

        <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fill,minmax(260px,1fr))',gap:'16px',marginBottom:'48px'}}>
          {demos.map((demo: {style:string;image_url:string;label?:string}, i:number) => (
            <div key={i} style={{background:'#111',border:'1px solid #1e1e1e',borderRadius:'14px',overflow:'hidden'}}>
              <img
                src={demo.image_url}
                alt={`${STYLE_LABELS[demo.style] || demo.style} AI QR code example`}
                style={{width:'100%',aspectRatio:'1',objectFit:'cover',display:'block'}}
                loading="lazy"
              />
              <div style={{padding:'14px'}}>
                <div style={{fontSize:'12px',fontWeight:700,color:gold,marginBottom:'4px'}}>
                  {STYLE_LABELS[demo.style] || demo.style}
                </div>
                <div style={{fontSize:'11px',color:'#555'}}>{demo.label || 'AI-generated, 100% scannable'}</div>
              </div>
            </div>
          ))}
        </div>

        <div style={{background:'#111',border:'1px solid rgba(201,162,39,.2)',borderRadius:'14px',padding:'32px',textAlign:'center'}}>
          <h2 style={{fontSize:'1.4rem',fontWeight:800,marginBottom:'8px'}}>Make one for your brand</h2>
          <p style={{color:'#888',marginBottom:'24px',lineHeight:1.6}}>
            Free to try — no signup, no credit card. Enter your URL and choose a style.
          </p>
          <div style={{display:'flex',gap:'12px',justifyContent:'center',flexWrap:'wrap'}}>
            <Link href="/free-qr-generator"
              style={{background:gold,color:'#000',padding:'13px 28px',borderRadius:'9px',fontWeight:700,textDecoration:'none',fontSize:'15px'}}>
              Generate Free →
            </Link>
            <Link href="/gig"
              style={{border:'1px solid #333',color:'#e5e5e5',padding:'13px 28px',borderRadius:'9px',fontWeight:700,textDecoration:'none',fontSize:'15px'}}>
              Order Custom $49
            </Link>
          </div>
          <p style={{color:'#444',fontSize:'13px',marginTop:'16px'}}>2 free generations/day · No signup · Instant download</p>
        </div>
      </div>
    </div>
  )
}
